In [1]:
import numpy as np

In [2]:
count = 0

In [3]:
R = int(input("Enter the number of rows:")) 
C = int(input("Enter the number of columns:")) 

Enter the number of rows:4
Enter the number of columns:7


In [4]:
print("Enter the entries in a single line (separated by space): ") 
entries = list(map(int, input().split())) 

Enter the entries in a single line (separated by space): 
1 0 0 0 1 1 1 0 1 0 0 1 1 0 0 0 1 0 1 0 1 0 0 0 1 0 1 1


In [5]:
matrix = np.array(entries).reshape(R, C) 
print(matrix) 

[[1 0 0 0 1 1 1]
 [0 1 0 0 1 1 0]
 [0 0 1 0 1 0 1]
 [0 0 0 1 0 1 1]]


In [6]:
I = np.eye(R)
M = matrix[0:R,0:R]

In [7]:
if np.all(np.equal(M, I)) :
    count = count + 1
    n = R
    while n + R < C :
        if np.all(np.equal(M, I)) :
            count = count + 1  
            M = matrix[n:n+R,n:n+R]
print(count)

1


In [8]:
p = count * 4
parity = matrix[:,p:]

In [9]:
print(parity)

[[1 1 1]
 [1 1 0]
 [1 0 1]
 [0 1 1]]


In [10]:
parity_t = parity.transpose() 

In [11]:
s_number = parity.shape[1]
s_number1 = s_number
rest = parity.shape[0]
restc = C - rest
print(rest)

4


In [12]:
I1 = np.eye(restc)

In [13]:
parity_t = np.array(parity_t)
I1 = np.array(I1)

In [14]:
print(parity_t)
print(I1)

[[1 1 1 0]
 [1 1 0 1]
 [1 0 1 1]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [15]:
check = np.concatenate((parity_t,I1),axis=1)

In [16]:
print(check)

[[1. 1. 1. 0. 1. 0. 0.]
 [1. 1. 0. 1. 0. 1. 0.]
 [1. 0. 1. 1. 0. 0. 1.]]


In [30]:
print("module generator(I,O);") 
print("    input [" + str(rest-1) + ":0] I;")
print("    output [" + str(s_number-1) + ":0] O;")

module generator(I,O);
    input [3:0] I;
    output [2:0] O;


In [34]:
axis = 0
restc1 = restc
mylist = []
while restc1 > 0 :
    str2 = " "
    p1 = np.array(parity[:,axis]) 
    p1 = np.where(p1)[0]
    p1 = abs(p1-restc)
    for i in p1:
        str2 = str2 + "I[" + str(i) + "]" + "^"
    str2 = str2[:-1] 
    #str2 = str2 + ")"
    mylist.append(str2)
    axis = axis + 1
    restc1 = restc1 - 1
print(mylist)
    

[' I[3]^I[2]^I[1]', ' I[3]^I[2]^I[0]', ' I[3]^I[1]^I[0]']


In [36]:
number = 0
while number < restc:
    print("    assign O[" + str(restc - number - 1) + "]=" + str(mylist[number]) + ";")
    number = number + 1
print("endmodule")

    assign O[2]= I[3]^I[2]^I[1];
    assign O[1]= I[3]^I[2]^I[0];
    assign O[0]= I[3]^I[1]^I[0];
endmodule


In [23]:
print("_______________________________________________________________________")

_______________________________________________________________________


In [40]:
print("module check(I,O);")
print("    input [" + str(C-1) + ":0] I" + ", [" + str(restc-1) + ":0] P;")
print("    output [" + str(s_number-1) + ":0] O;")

module check(I,O);
    input [6:0] I, [2:0] P;
    output [2:0] O;


In [41]:
m = 0
datalist = []

while m < s_number :
    str3 = " "
    check1 = np.array(check[m,:])
    check1 = np.where(check1)[0]
    check1 = check1-restc
    for c in check1:
        
        if c <= 0 :
            c1 = -c
            str3 = str3 + "I[" + str(c1) + "]" + "^"
        else:
            c1 = abs(c-restc)
            str3 = str3 + "P[" + str(c1) + "]" + "^"
    str3 = str3[:-1]
    datalist.append(str3)
    m = m + 1 
print(datalist)

[' I[3]^I[2]^I[1]^P[2]', ' I[3]^I[2]^I[0]^P[1]', ' I[3]^I[1]^I[0]^P[0]']


In [37]:
numbs = 0
while numbs < s_number:
    print("    assign O[" + str(s_number - numbs - 1) + "]=" + str(datalist[numbs]) + ";")
    numbs = numbs + 1
print("endmodule")

    assign O[2]= d[3]^d[2]^d[1]^p[2];
    assign O[1]= d[3]^d[2]^d[0]^p[1];
    assign O[0]= d[3]^d[1]^d[0]^p[0];
endmodule
